spring.application.name=turf-score-calculator
logging.level.root=info

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
endpoints.shutdown.enabled=true

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/scorecalc
spring.datasource.username=scorecalc-user
spring.datasource.password=scorecalc-password

# create and drop table, good for testing, production set to none or comment it
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
